### ISSUE TITLE
Add check for list of this pages that those pages are exists and fine

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE-QA/testing-helpcenter#399]
https://helpcenter.onlyoffice.com/ONLYOFFICE-Editors/ONLYOFFICE-Document-Editor/UsageInstructions/InsertContentControls.aspx
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx
https://helpcenter.onlyoffice.com/server/developer-edition/docker/docker-installation.aspx
https://helpcenter.onlyoffice.com/server/docker/document/add-interface-language.aspx
https://helpcenter.onlyoffice.com/server/document/available-languages.aspx
https://helpcenter.onlyoffice.com/server/document/document-server-proxy.aspx
https://helpcenter.onlyoffice.com/installation/docs-developer-install-windows.aspx
https://helpcenter.onlyoffice.com/installation/docs-developer-install-ubuntu.aspx
https://helpcenter.onlyoffice.com/installation/docs-developer-install-docker.aspx
https://helpcenter.onlyoffice.com/installation/docs-community-https-linux.aspx
https://helpcenter.onlyoffice.com/installation/docs-community-install-fonts-linux.aspx
https://helpcenter.onlyoffice.com/installation/docs-developer-change-theme.aspx

https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#wopi-enable
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#AutoAssembly
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#SecretKey
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#Token
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#services-CoAuthoring-server-savetimeoutdelay
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#services-CoAuthoring-server-assemblyFormatAsOrigin
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#services-CoAuthoring-server-tokenRequiredParams
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#WOPI
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#wopi-enable
https://helpcenter.onlyoffice.com/installation/docs-developer-configuring.aspx#IPFilter

**Comment by Qobiljonn** [comment]
Implemented in #424
